/**
 * Automatically generated by Zserio Java generator version 1.1.1 using Zserio core 2.14.1.
 * Generator setup: writerCode, pubsubCode, serviceCode, sqlCode.
 */

package tutorial;

public class Experience implements zserio.runtime.io.Writer, zserio.runtime.SizeOf
{
    public Experience()
    {
    }

    public Experience(zserio.runtime.io.BitStreamReader in)
            throws java.io.IOException
    {
        read(in);
    }

    public Experience(
            byte yearsOfExperience_,
            tutorial.Language programmingLanguage_)
    {
        setYearsOfExperience(yearsOfExperience_);
        setProgrammingLanguage(programmingLanguage_);
    }

    @Override
    public int bitSizeOf()
    {
        return bitSizeOf(0);
    }

    @Override
    public int bitSizeOf(long bitPosition)
    {
        long endBitPosition = bitPosition;

        endBitPosition += 6;
        endBitPosition += programmingLanguage_.bitSizeOf(endBitPosition);

        return (int)(endBitPosition - bitPosition);
    }

    public byte getYearsOfExperience()
    {
        return yearsOfExperience_;
    }

    public void setYearsOfExperience(byte yearsOfExperience_)
    {
        this.yearsOfExperience_ = yearsOfExperience_;
    }

    public tutorial.Language getProgrammingLanguage()
    {
        return programmingLanguage_;
    }

    public void setProgrammingLanguage(tutorial.Language programmingLanguage_)
    {
        this.programmingLanguage_ = programmingLanguage_;
    }

    @Override
    public boolean equals(java.lang.Object obj)
    {
        if (obj instanceof Experience)
        {
            final Experience that = (Experience)obj;

            return
                    yearsOfExperience_ == that.yearsOfExperience_ &&
                    ((programmingLanguage_ == null) ? that.programmingLanguage_ == null : programmingLanguage_.getValue() == that.programmingLanguage_.getValue());
        }

        return false;
    }

    @Override
    public int hashCode()
    {
        int result = zserio.runtime.HashCodeUtil.HASH_SEED;

        result = zserio.runtime.HashCodeUtil.calcHashCode(result, yearsOfExperience_);
        result = zserio.runtime.HashCodeUtil.calcHashCode(result, programmingLanguage_);

        return result;
    }

    public void read(zserio.runtime.io.BitStreamReader in)
            throws java.io.IOException
    {
        yearsOfExperience_ = (byte)in.readBits(6);

        programmingLanguage_ = tutorial.Language.readEnum(in);
    }

    @Override
    public long initializeOffsets()
    {
        return initializeOffsets(0);
    }

    @Override
    public long initializeOffsets(long bitPosition)
    {
        long endBitPosition = bitPosition;

        endBitPosition += 6;
        endBitPosition += programmingLanguage_.bitSizeOf(endBitPosition);

        return endBitPosition;
    }

    @Override
    public void write(zserio.runtime.io.BitStreamWriter out) throws java.io.IOException
    {
        out.writeBits(yearsOfExperience_, 6);

        programmingLanguage_.write(out);
    }

    private byte yearsOfExperience_;
    private tutorial.Language programmingLanguage_;
}
