/**
 * Automatically generated by Zserio Java extension version 2.12.0.
 * Generator setup: writerCode, pubsubCode, serviceCode, sqlCode.
 */

package tutorial;

public class Experience implements zserio.runtime.io.PackableWriter, zserio.runtime.PackableSizeOf
{
    public static final class ZserioPackingContext extends zserio.runtime.array.PackingContext
    {
        public ZserioPackingContext()
        {
            yearsOfExperience_ = new zserio.runtime.array.DeltaContext();
            programmingLanguage_ = new zserio.runtime.array.DeltaContext();
        }

        public zserio.runtime.array.DeltaContext getYearsOfExperience()
        {
            return yearsOfExperience_;
        }

        public zserio.runtime.array.DeltaContext getProgrammingLanguage()
        {
            return programmingLanguage_;
        }

        private zserio.runtime.array.DeltaContext yearsOfExperience_;
        private zserio.runtime.array.DeltaContext programmingLanguage_;
    };

    public Experience()
    {
    }

    public Experience(zserio.runtime.io.BitStreamReader in)
            throws java.io.IOException
    {
        read(in);
    }

    public Experience(zserio.runtime.array.PackingContext context, zserio.runtime.io.BitStreamReader in)
            throws java.io.IOException
    {
        read(context, in);
    }

    public Experience(
            byte yearsOfExperience_,
            tutorial.Language programmingLanguage_)
    {
        setYearsOfExperience(yearsOfExperience_);
        setProgrammingLanguage(programmingLanguage_);
    }

    @Override
    public void initPackingContext(zserio.runtime.array.PackingContext context)
    {
        final ZserioPackingContext zserioContext = context.cast();
        zserioContext.getYearsOfExperience().init(new zserio.runtime.array.ArrayTraits.BitFieldByteArrayTraits((int)(6)),
                new zserio.runtime.array.ArrayElement.ByteArrayElement(yearsOfExperience_));
        programmingLanguage_.initPackingContext(zserioContext.getProgrammingLanguage());
    }

    @Override
    public int bitSizeOf()
    {
        return bitSizeOf(0);
    }

    @Override
    public int bitSizeOf(long bitPosition)
    {
        long endBitPosition = bitPosition;

        endBitPosition += 6;
        endBitPosition += programmingLanguage_.bitSizeOf(endBitPosition);

        return (int)(endBitPosition - bitPosition);
    }

    @Override
    public int bitSizeOf(zserio.runtime.array.PackingContext context, long bitPosition)
    {
        final ZserioPackingContext zserioContext = context.cast();
        long endBitPosition = bitPosition;

        endBitPosition += zserioContext.getYearsOfExperience().bitSizeOf(new zserio.runtime.array.ArrayTraits.BitFieldByteArrayTraits((int)(6)),
                new zserio.runtime.array.ArrayElement.ByteArrayElement(yearsOfExperience_));
        endBitPosition += programmingLanguage_.bitSizeOf(zserioContext.getProgrammingLanguage(), endBitPosition);

        return (int)(endBitPosition - bitPosition);
    }

    public byte getYearsOfExperience()
    {
        return yearsOfExperience_;
    }

    public void setYearsOfExperience(byte yearsOfExperience_)
    {
        this.yearsOfExperience_ = yearsOfExperience_;
    }

    public tutorial.Language getProgrammingLanguage()
    {
        return programmingLanguage_;
    }

    public void setProgrammingLanguage(tutorial.Language programmingLanguage_)
    {
        this.programmingLanguage_ = programmingLanguage_;
    }

    @Override
    public boolean equals(java.lang.Object obj)
    {
        if (obj instanceof Experience)
        {
            final Experience that = (Experience)obj;

            return
                    yearsOfExperience_ == that.yearsOfExperience_ &&
                    ((programmingLanguage_ == null) ? that.programmingLanguage_ == null : programmingLanguage_.getValue() == that.programmingLanguage_.getValue());
        }

        return false;
    }

    @Override
    public int hashCode()
    {
        int result = zserio.runtime.HashCodeUtil.HASH_SEED;

        result = zserio.runtime.HashCodeUtil.calcHashCode(result, yearsOfExperience_);
        result = zserio.runtime.HashCodeUtil.calcHashCode(result, programmingLanguage_);

        return result;
    }

    public void read(zserio.runtime.io.BitStreamReader in)
            throws java.io.IOException
    {
        yearsOfExperience_ = (byte)in.readBits(6);

        programmingLanguage_ = tutorial.Language.readEnum(in);
    }

    public void read(zserio.runtime.array.PackingContext context, zserio.runtime.io.BitStreamReader in)
            throws java.io.IOException
    {
        final ZserioPackingContext zserioContext = context.cast();
        yearsOfExperience_ = ((zserio.runtime.array.ArrayElement.ByteArrayElement)
                zserioContext.getYearsOfExperience().read(new zserio.runtime.array.ArrayTraits.BitFieldByteArrayTraits((int)(6)), in)).get();

        programmingLanguage_ = tutorial.Language.readEnum(zserioContext.getProgrammingLanguage(), in);
    }

    @Override
    public long initializeOffsets()
    {
        return initializeOffsets(0);
    }

    @Override
    public long initializeOffsets(long bitPosition)
    {
        long endBitPosition = bitPosition;

        endBitPosition += 6;
        endBitPosition += programmingLanguage_.bitSizeOf(endBitPosition);

        return endBitPosition;
    }

    @Override
    public long initializeOffsets(zserio.runtime.array.PackingContext context, long bitPosition)
    {
        final ZserioPackingContext zserioContext = context.cast();
        long endBitPosition = bitPosition;

        endBitPosition += zserioContext.getYearsOfExperience().bitSizeOf(new zserio.runtime.array.ArrayTraits.BitFieldByteArrayTraits((int)(6)),
                new zserio.runtime.array.ArrayElement.ByteArrayElement(yearsOfExperience_));
        endBitPosition = programmingLanguage_.initializeOffsets(zserioContext.getProgrammingLanguage(), endBitPosition);

        return endBitPosition;
    }

    @Override
    public void write(zserio.runtime.io.BitStreamWriter out) throws java.io.IOException
    {
        out.writeBits(yearsOfExperience_, 6);

        programmingLanguage_.write(out);
    }

    @Override
    public void write(zserio.runtime.array.PackingContext context, zserio.runtime.io.BitStreamWriter out)
            throws java.io.IOException
    {
        final ZserioPackingContext zserioContext = context.cast();
        zserioContext.getYearsOfExperience().write(new zserio.runtime.array.ArrayTraits.BitFieldByteArrayTraits((int)(6)), out,
                new zserio.runtime.array.ArrayElement.ByteArrayElement(yearsOfExperience_));

        programmingLanguage_.write(zserioContext.getProgrammingLanguage(), out);
    }

    private byte yearsOfExperience_;
    private tutorial.Language programmingLanguage_;
}
