/**
 * Automatically generated by Zserio Java extension version 2.2.0.
 * Generator setup: writerCode, pubsubCode, serviceCode, sqlCode.
 */

package tutorial;

public enum Role implements zserio.runtime.io.InitializeOffsetsWriter,
        zserio.runtime.SizeOf, zserio.runtime.ZserioEnum
{
    DEVELOPER((short)0),
    TEAM_LEAD((short)1),
    CTO((short)2);

    private Role(short value)
    {
        this.value = value;
    }

    public short getValue()
    {
        return value;
    }

    @Override
    public java.lang.Number getGenericValue()
    {
        return value;
    }

    @Override
    public int bitSizeOf()
    {
        return bitSizeOf(0);
    }

    @Override
    public int bitSizeOf(long bitPosition)
    {
        return 8;
    }

    @Override
    public long initializeOffsets(long bitPosition) throws zserio.runtime.ZserioError
    {
        return bitPosition + bitSizeOf(bitPosition);
    }

    @Override
    public void write(zserio.runtime.io.BitStreamWriter out) throws java.io.IOException
    {
        write(out, false);
    }

    @Override
    public void write(zserio.runtime.io.BitStreamWriter out, boolean callInitializeOffsets)
            throws java.io.IOException
    {
        out.writeUnsignedByte(getValue());
    }

    public static Role readEnum(zserio.runtime.io.BitStreamReader in) throws java.io.IOException
    {
        return toEnum(in.readUnsignedByte());
    }

    public static Role toEnum(short value)
    {
        switch (value)
        {
            case (short)0:
                return DEVELOPER;
            case (short)1:
                return TEAM_LEAD;
            case (short)2:
                return CTO;
            default:
                throw new java.lang.IllegalArgumentException(
                        "Unknown value for enumeration Role: " + value + "!");
        }
    }

    private short value;
}
